---
- name: Deploy Kubernetes Resources
  hosts: localhost
  gather_facts: false
  tasks:
    - name: cgclient
      k8s:
        state: absent
        src: k8s/cgclient-deployment.yaml

    - name: cgclient service
      k8s:
        state: absent
        src: k8s/cgclient-service.yaml

    - name: cgclient PVC
      k8s:
        state: absent
        src: k8s/cgclient-claim0-persistentvolumeclaim.yaml
###############################################
    - name: cgserver
      k8s:
        state: absent
        src: k8s/cgserver-deployment.yaml

    - name: cgserver service
      k8s:
        state: absent
        src: k8s/cgserver-service.yaml

    - name: cgserver PVC
      k8s:
        state: absent
        src: k8s/cgserver-claim0-persistentvolumeclaim.yaml
###############################################
    - name: ddosclient
      k8s:
        state: absent
        src: k8s/ddosclient-deployment.yaml

    - name: ddosclient service
      k8s:
        state: absent
        src: k8s/ddosclient-service.yaml

    - name: ddosclient PVC
      k8s:
        state: absent
        src: k8s/ddosclient-claim0-persistentvolumeclaim.yaml
###############################################
    - name: ddosserver
      k8s:
        state: absent
        src: k8s/ddosserver-deployment.yaml

    - name: ddosserver service
      k8s:
        state: absent
        src: k8s/ddosserver-service.yaml

    - name: ddosserver PVC
      k8s:
        state: absent
        src: k8s/ddosserver-claim0-persistentvolumeclaim.yaml