apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cgserver
  name: cgserver
  namespace: default
spec:
  ports:
    - name: "2224"
      port: 2224
      targetPort: 22
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: cgserver
status:
  loadBalancer: {}
