---
- name: Topology Configuration
  hosts: localhost
  gather_facts: no
  vars:
    cgclients:
      - name: cgclient1
        pod: cgclient1

    ddosclients:
      - name: ddosclient1
        pod: ddosclient1


  tasks:
    - name: Configure cgserver
      command: kubectl exec -it -n ddos cgserver -- python3 cgserver-config.py
    - name: Configure ddosserver
      command: kubectl exec -it -n ddos ddosserver -- python3 ddosserver-config.py


    - name: Get cgserver IP
      shell: "kubectl exec -n ddos cgserver -- ip addr show eth1 | awk '/inet / {gsub(/\\/\\/[0-9]+/, \"\", $2); print $2}'"
      register: cgserver_ip_output
      changed_when: false
      ignore_errors: yes

    - name: Extract IP from cgserver_ip_output
      set_fact:
        cgserver_ip: "{{ cgserver_ip_output.stdout.split('/')[0] }}"
        
    - name: Debug cgserverip
      debug:
        var: cgserver_ip


    - name: Get ddosserver IP
      shell: "kubectl exec -n ddos ddosserver -- ip addr show eth1 | awk '/inet / {gsub(/\\/\\/[0-9]+/, \"\", $2); print $2}'"
      register: ddosserver_ip_output
      changed_when: false
      ignore_errors: yes

    - name: Set ddosserver IP as a fact
      set_fact:
        ddosserver_ip: "{{ ddosserver_ip_output.stdout.split('/')[0] }}"
        
    - name: Debug ddosserverip
      debug:
        var: ddosserver_ip




    - name: "Configure {{ item.name }}"
      command: kubectl exec -it -n ddos {{ item.pod }} -- python3 {{ item.name }}-config.py
      loop: "{{ cgclients + ddosclients }}"


    - name: Set environment variables for cgclient
      command: kubectl exec -it -n ddos {{ item.pod }} -- /bin/bash -c "export cgserver=\"{{ cgserver_ip }}\""
      loop: "{{ cgclients }}"

    - name: Set environment variables for ddosclient
      command: kubectl exec -it -n ddos {{ item.pod }} -- /bin/bash -c "export ddosserver=\"{{ ddosserver_ip }}\""
      loop: "{{ ddosclients }}"
