---
- name: Topology Deployment using kne
  hosts: localhost
  gather_facts: no
  tasks: 
 #--------------------------------------------Deploy kne---------------------------------------------------------------------------
 
    - name: Deploy topology
      shell: kne create ~/kne/examples/arista/b5gemini/TopologiaB5gemini.yaml # Configure the path where the kne topology file is

    - name: Deploy external
      shell: kubectl apply -f ~/kne/examples/arista/b5gemini/pod-external.yaml