---
- name: Topology Deployment using kne
  hosts: localhost
  gather_facts: no
  tasks: 
 
    - name: Deploy topology
      shell: kne create ~/kne/examples/cisco/conversion/Topologias/ddos/TopologiaDdos.yaml