---
- name: Execute task in pods
  hosts: localhost
  gather_facts: no
  vars:
    cgclients: []
    ddosclients: []

  tasks:
#--------------------------------------Configuration------------------------------------------------------------------------------------
    - name: Include client counts
      include_vars:
        file: clients_number.yaml
  
    - name: Crear cgclients
      set_fact:
        cgclients: "{{ cgclients + [{'name': 'cgclient' ~ item, 'pod': 'cgclient' ~ item}] }}"
      loop: "{{ range(1, cg_count + 1)|list }}"
    
    - name: Crear ddosclients
      set_fact:
        ddosclients: "{{ ddosclients + [{'name': 'ddosclient' ~ item, 'pod': 'ddosclient' ~ item}] }}"
      loop: "{{ range(1, ddos_count + 1)|list }}"
    
    - name: Include server IPs
      include_vars:
        file: "{{ playbook_dir }}/server_ips.yaml"

    - name: Debug loaded server IPs
      debug:
        var: ddosserver_ip

    - name: Debug loaded server IPs
      debug:
        var: cgserver_ip
        
    - name: Debug loaded server IPs
      debug:
        var: internet_ip
      

#---------------------------------Tasks execution---------------------------------------------------------------------------------------
    #cgserver:
    - name: Start ACROSSserver.py
      shell: kubectl exec -n ddos cgserver -- python3 ACROSSserver.py 
      async: 3600
      poll: 0

    
    #ddosserver:
    - name: Start ngnix
      shell: kubectl exec -n ddos ddosserver -- nginx -g 'daemon off;'
      async: 3600
      poll: 0

    - name: Start bind9
      shell: kubectl exec -n ddos ddosserver -- service bind9 start
      
      
    #Cglient:
    - name: Execute ACROSSfile_transfer
      shell: kubectl exec -n ddos {{ item.pod }} -- env https_proxy="http://{{ internet_ip }}:3128" https_proxy="http://{{ internet_ip }}:3128" python3 ACROSSfile_transfer.py https://ia801802.us.archive.org/15/items/alexander-the-great-1997-part-1/Alexander%20The%20Great%20%281997%29%20Part%201.mp4 #set url
      loop: "{{ cgclients }}"
      async: 3600 
      poll: 0

    - name: Execute ACROSSconsuming_video.py
      shell: kubectl exec -n ddos {{ item.pod }} -- env https_proxy="http://{{ internet_ip }}:3128" https_proxy="http://{{ internet_ip }}:3128" python3 ACROSSconsuming_video.py https://www.youtube.com/watch?v=-No-226O0tg 30 #set time and url
      loop: "{{ cgclients }}"
      async: 3600 
      poll: 0
      register: acrossclient_result
    
    - name: Execute ACROSSshorts.py
      shell: kubectl exec -n ddos {{ item.pod }} -- env https_proxy="http://{{ internet_ip }}:3128" https_proxy="http://{{ internet_ip }}:3128" python3 ACROSSshorts.py 30 #set time
      loop: "{{ cgclients }}"
      async: 3600 
      poll: 0
      register: acrossshorts_result
      
    - name: Execute ACROSSclient.py
      shell: kubectl exec -n ddos {{ item.pod }} -- env cgserver={{ cgserver_ip }} python3 ACROSSclient.py 10000 #set multiplier
      loop: "{{ cgclients }}"
      async: 3600 
      poll: 0

    - name: Execute CGTest19.sh
      shell: kubectl exec -n ddos {{ item.pod }} -- env https_proxy="http://{{ internet_ip }}:3128" https_proxy="http://{{ internet_ip }}:3128" ./CGTest19.sh web_links.txt
      loop: "{{ cgclients }}"
      async: 3600 
      poll: 0
      
      
    #ddosclient:
    - name: Execute hping3.sh
      shell: kubectl exec -n ddos {{ item.pod }} -- env ddosserver={{ ddosserver_ip }} /bin/bash -c 'sudo hping3 -c 100 -d 200 -S $ddosserver -w 1232 -p 43 --flood'
      loop: "{{ ddosclients }}"
      async: 3600 
      poll: 0

    - name: Execute vegeta.sh
      shell: kubectl exec -n ddos {{ item.pod }} -- env ddosserver={{ ddosserver_ip }} ./vegeta.sh 30
      loop: "{{ ddosclients }}"
      async: 3600 
      poll: 0

    - name: Execute dns_scapy
      shell: kubectl exec -n ddos {{ item.pod }} -- env ddosserver={{ ddosserver_ip }} python3 dns_scapy.py 100
      loop: "{{ ddosclients }}"
      async: 3600 
      poll: 0
    
#    - name: Execute quick_scapy
#      shell: kubectl exec -n ddos {{ item.pod }} -- python3 quic-scapy/scapy_demo.py
#      loop: "{{ ddosclients }}"
#      async: 3600 
#      poll: 0
#
#     - name: Execute water_torture
#       shell: kubectl exec -it {{ item.pod }} -- go run DNSWaterTorture/watertorture.go -count 100 -s ddosserver -t ddosserver
#       loop: "{{ ddosclients }}"
#       async: 3600 
#       poll: 0
#
#     - name: Execute dns_proxy
#       shell: kubectl exec -it {{ item.pod }} -- /home/cognet/dnscrypt-proxy-linux_x86_64-2.1.5/config.sh
#       loop: "{{ ddosclients }}"
#       async: 3600 
#       poll: 0

#---------------------------------Waiting tasks---------------------------------------------------------------------------------------

    - name: Waiting for ACROSSconsuming_video.py and ACROSSshort.py finish
      async_status: 
        jid: "{{ item.ansible_job_id }}"
      loop: "{{ (acrossclient_result.results | default([])) + (acrossshorts_result.results | default([])) }}"
      register: acrossclient_jobs
      until: acrossclient_jobs.finished 
      retries: 999
      delay: 15
      