apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ddosclient
  name: ddosclient
  namespace: default
spec:
  ports:
    - name: "2226"
      port: 2226
      targetPort: 22
  selector:
    io.kompose.service: ddosclient
status:
  loadBalancer: {}
